from PySide import QtCore, QtGui

class Ui_Window1(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.setWindowModality(QtCore.Qt.WindowModal)
        Window.resize(409, 274)
        self.verticalLayoutWidget = QtGui.QWidget(Window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 80, 251, 42))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LoginText = QtGui.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.LoginText.setFont(font)
        self.LoginText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.LoginText.setEchoMode(QtGui.QLineEdit.Normal)
        self.LoginText.setObjectName("LoginText")
        self.verticalLayout.addWidget(self.LoginText)
        self.verticalLayoutWidget_2 = QtGui.QWidget(Window)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(150, 140, 251, 42))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PasswordText = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.PasswordText.setFont(font)
        self.PasswordText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.PasswordText.setEchoMode(QtGui.QLineEdit.Normal)
        self.PasswordText.setObjectName("PasswordText")
        self.verticalLayout_2.addWidget(self.PasswordText)
        self.verticalLayoutWidget_4 = QtGui.QWidget(Window)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 80, 141, 41))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.LoginLabel = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LoginLabel.setFont(font)
        self.LoginLabel.setTextFormat(QtCore.Qt.AutoText)
        self.LoginLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LoginLabel.setObjectName("LoginLabel")
        self.verticalLayout_4.addWidget(self.LoginLabel)
        self.verticalLayoutWidget_5 = QtGui.QWidget(Window)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 140, 141, 41))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.PasswordLabel = QtGui.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.verticalLayout_5.addWidget(self.PasswordLabel)
        self.verticalLayoutWidget_3 = QtGui.QWidget(Window)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 411, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Error = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.Error.setFont(font)
        self.Error.setText("")
        self.Error.setAlignment(QtCore.Qt.AlignCenter)
        self.Error.setObjectName("Error")
        self.verticalLayout_3.addWidget(self.Error)
        self.verticalLayoutWidget_6 = QtGui.QWidget(Window)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(150, 190, 251, 47))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton = QtGui.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        Window.setWindowTitle(QtGui.QApplication.translate("Window", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.LoginLabel.setText(QtGui.QApplication.translate("Window", "Login:", None, QtGui.QApplication.UnicodeUTF8))
        self.PasswordLabel.setText(QtGui.QApplication.translate("Window", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Window", "Войти", None, QtGui.QApplication.UnicodeUTF8))

class Ui_buttons(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(478, 289)
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 481, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ShowClient = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.ShowClient.setFont(font)
        self.ShowClient.setObjectName("ShowClient")
        self.verticalLayout.addWidget(self.ShowClient)
        self.DeleteClient = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.DeleteClient.setFont(font)
        self.DeleteClient.setObjectName("DeleteClient")
        self.verticalLayout.addWidget(self.DeleteClient)
        self.ReNameClient = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.ReNameClient.setFont(font)
        self.ReNameClient.setObjectName("ReNameClient")
        self.verticalLayout.addWidget(self.ReNameClient)
        self.AddClient = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.AddClient.setFont(font)
        self.AddClient.setObjectName("AddClient")
        self.verticalLayout.addWidget(self.AddClient)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.ShowClient.setText(
            QtGui.QApplication.translate("Form", "Показать клиентов", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteClient.setText(
            QtGui.QApplication.translate("Form", "Удалить Клиента", None, QtGui.QApplication.UnicodeUTF8))
        self.ReNameClient.setText(
            QtGui.QApplication.translate("Form", "Изменить Клиента", None, QtGui.QApplication.UnicodeUTF8))
        self.AddClient.setText(
            QtGui.QApplication.translate("Form", "Добавить клента", None, QtGui.QApplication.UnicodeUTF8))

class Ui_Data(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(852, 501)
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 851, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lbl.setFont(font)
        self.lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl.setObjectName("lbl")
        self.verticalLayout.addWidget(self.lbl)
        self.gridLayoutWidget = QtGui.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 60, 851, 441))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateTimeEdit.setFrame(False)
        self.dateTimeEdit.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.dateTimeEdit.setKeyboardTracking(False)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_2.setFont(font)
        self.dateTimeEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateTimeEdit_2.setFrame(False)
        self.dateTimeEdit_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_2.setKeyboardTracking(False)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout.addWidget(self.dateTimeEdit_2, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 9, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_15.setFont(font)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_16.setFont(font)
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_17.setFont(font)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_18.setFont(font)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 5, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_19.setFont(font)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 6, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_20.setFont(font)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_21.setFont(font)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 8, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_22.setFont(font)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 9, 1, 1, 1)
        self.dateTimeEdit_5 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_5.setFont(font)
        self.dateTimeEdit_5.setFrame(False)
        self.dateTimeEdit_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_5.setKeyboardTracking(False)
        self.dateTimeEdit_5.setObjectName("dateTimeEdit_5")
        self.gridLayout.addWidget(self.dateTimeEdit_5, 2, 2, 1, 1)
        self.dateTimeEdit_6 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_6.setFont(font)
        self.dateTimeEdit_6.setFrame(False)
        self.dateTimeEdit_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_6.setKeyboardTracking(False)
        self.dateTimeEdit_6.setObjectName("dateTimeEdit_6")
        self.gridLayout.addWidget(self.dateTimeEdit_6, 3, 2, 1, 1)
        self.dateTimeEdit_7 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_7.setFont(font)
        self.dateTimeEdit_7.setFrame(False)
        self.dateTimeEdit_7.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_7.setKeyboardTracking(False)
        self.dateTimeEdit_7.setObjectName("dateTimeEdit_7")
        self.gridLayout.addWidget(self.dateTimeEdit_7, 4, 2, 1, 1)
        self.dateTimeEdit_8 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_8.setFont(font)
        self.dateTimeEdit_8.setFrame(False)
        self.dateTimeEdit_8.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_8.setKeyboardTracking(False)
        self.dateTimeEdit_8.setObjectName("dateTimeEdit_8")
        self.gridLayout.addWidget(self.dateTimeEdit_8, 5, 2, 1, 1)
        self.dateTimeEdit_9 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_9.setFont(font)
        self.dateTimeEdit_9.setFrame(False)
        self.dateTimeEdit_9.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_9.setKeyboardTracking(False)
        self.dateTimeEdit_9.setObjectName("dateTimeEdit_9")
        self.gridLayout.addWidget(self.dateTimeEdit_9, 6, 2, 1, 1)
        self.dateTimeEdit_10 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_10.setFont(font)
        self.dateTimeEdit_10.setFrame(False)
        self.dateTimeEdit_10.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_10.setKeyboardTracking(False)
        self.dateTimeEdit_10.setObjectName("dateTimeEdit_10")
        self.gridLayout.addWidget(self.dateTimeEdit_10, 7, 2, 1, 1)
        self.dateTimeEdit_11 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_11.setFont(font)
        self.dateTimeEdit_11.setFrame(False)
        self.dateTimeEdit_11.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_11.setKeyboardTracking(False)
        self.dateTimeEdit_11.setObjectName("dateTimeEdit_11")
        self.gridLayout.addWidget(self.dateTimeEdit_11, 8, 2, 1, 1)
        self.dateTimeEdit_12 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_12.setFont(font)
        self.dateTimeEdit_12.setFrame(False)
        self.dateTimeEdit_12.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_12.setKeyboardTracking(False)
        self.dateTimeEdit_12.setObjectName("dateTimeEdit_12")
        self.gridLayout.addWidget(self.dateTimeEdit_12, 9, 2, 1, 1)
        self.dateTimeEdit_13 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_13.setFont(font)
        self.dateTimeEdit_13.setFrame(False)
        self.dateTimeEdit_13.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_13.setKeyboardTracking(False)
        self.dateTimeEdit_13.setObjectName("dateTimeEdit_13")
        self.gridLayout.addWidget(self.dateTimeEdit_13, 2, 3, 1, 1)
        self.dateTimeEdit_14 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_14.setFont(font)
        self.dateTimeEdit_14.setFrame(False)
        self.dateTimeEdit_14.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_14.setKeyboardTracking(False)
        self.dateTimeEdit_14.setObjectName("dateTimeEdit_14")
        self.gridLayout.addWidget(self.dateTimeEdit_14, 3, 3, 1, 1)
        self.dateTimeEdit_15 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_15.setFont(font)
        self.dateTimeEdit_15.setFrame(False)
        self.dateTimeEdit_15.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_15.setKeyboardTracking(False)
        self.dateTimeEdit_15.setObjectName("dateTimeEdit_15")
        self.gridLayout.addWidget(self.dateTimeEdit_15, 4, 3, 1, 1)
        self.dateTimeEdit_16 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_16.setFont(font)
        self.dateTimeEdit_16.setFrame(False)
        self.dateTimeEdit_16.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_16.setKeyboardTracking(False)
        self.dateTimeEdit_16.setObjectName("dateTimeEdit_16")
        self.gridLayout.addWidget(self.dateTimeEdit_16, 5, 3, 1, 1)
        self.dateTimeEdit_17 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_17.setFont(font)
        self.dateTimeEdit_17.setFrame(False)
        self.dateTimeEdit_17.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_17.setKeyboardTracking(False)
        self.dateTimeEdit_17.setObjectName("dateTimeEdit_17")
        self.gridLayout.addWidget(self.dateTimeEdit_17, 6, 3, 1, 1)
        self.dateTimeEdit_18 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_18.setFont(font)
        self.dateTimeEdit_18.setFrame(False)
        self.dateTimeEdit_18.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_18.setKeyboardTracking(False)
        self.dateTimeEdit_18.setObjectName("dateTimeEdit_18")
        self.gridLayout.addWidget(self.dateTimeEdit_18, 7, 3, 1, 1)
        self.dateTimeEdit_19 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_19.setFont(font)
        self.dateTimeEdit_19.setFrame(False)
        self.dateTimeEdit_19.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_19.setKeyboardTracking(False)
        self.dateTimeEdit_19.setObjectName("dateTimeEdit_19")
        self.gridLayout.addWidget(self.dateTimeEdit_19, 8, 3, 1, 1)
        self.dateTimeEdit_20 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_20.setFont(font)
        self.dateTimeEdit_20.setFrame(False)
        self.dateTimeEdit_20.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_20.setKeyboardTracking(False)
        self.dateTimeEdit_20.setObjectName("dateTimeEdit_20")
        self.gridLayout.addWidget(self.dateTimeEdit_20, 9, 3, 1, 1)
        self.dateTimeEdit_3 = QtGui.QDateTimeEdit(Form)
        self.dateTimeEdit_3.setGeometry(QtCore.QRect(1196, 300, 243, 33))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_3.setFont(font)
        self.dateTimeEdit_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateTimeEdit_3.setFrame(False)
        self.dateTimeEdit_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_3.setKeyboardTracking(False)
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.dateTimeEdit_4 = QtGui.QDateTimeEdit(Form)
        self.dateTimeEdit_4.setGeometry(QtCore.QRect(947, 300, 243, 33))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_4.setFont(font)
        self.dateTimeEdit_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateTimeEdit_4.setFrame(False)
        self.dateTimeEdit_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_4.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.dateTimeEdit_4.setKeyboardTracking(False)
        self.dateTimeEdit_4.setObjectName("dateTimeEdit_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl.setText(
            QtGui.QApplication.translate("Form", "Клиенты на сегодня", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Клиент", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Парикхмахер", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(
            QtGui.QApplication.translate("Form", "Время окончания", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Время начала", None, QtGui.QApplication.UnicodeUTF8))