from PySide import QtCore, QtGui

class Ui_Window1(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.setWindowModality(QtCore.Qt.WindowModal)
        Window.resize(409, 274)
        self.verticalLayoutWidget = QtGui.QWidget(Window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 80, 251, 42))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LoginText = QtGui.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.LoginText.setFont(font)
        self.LoginText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.LoginText.setEchoMode(QtGui.QLineEdit.Normal)
        self.LoginText.setObjectName("LoginText")
        self.verticalLayout.addWidget(self.LoginText)
        self.verticalLayoutWidget_2 = QtGui.QWidget(Window)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(150, 140, 251, 42))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PasswordText = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.PasswordText.setFont(font)
        self.PasswordText.setInputMethodHints(QtCore.Qt.ImhNone)
        self.PasswordText.setEchoMode(QtGui.QLineEdit.Normal)
        self.PasswordText.setObjectName("PasswordText")
        self.verticalLayout_2.addWidget(self.PasswordText)
        self.verticalLayoutWidget_4 = QtGui.QWidget(Window)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 80, 141, 41))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.LoginLabel = QtGui.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.LoginLabel.setFont(font)
        self.LoginLabel.setTextFormat(QtCore.Qt.AutoText)
        self.LoginLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LoginLabel.setObjectName("LoginLabel")
        self.verticalLayout_4.addWidget(self.LoginLabel)
        self.verticalLayoutWidget_5 = QtGui.QWidget(Window)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 140, 141, 41))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.PasswordLabel = QtGui.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.verticalLayout_5.addWidget(self.PasswordLabel)
        self.verticalLayoutWidget_3 = QtGui.QWidget(Window)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(-1, -1, 411, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Error = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.Error.setFont(font)
        self.Error.setText("")
        self.Error.setAlignment(QtCore.Qt.AlignCenter)
        self.Error.setObjectName("Error")
        self.verticalLayout_3.addWidget(self.Error)
        self.verticalLayoutWidget_6 = QtGui.QWidget(Window)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(150, 190, 251, 47))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton = QtGui.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        Window.setWindowTitle(QtGui.QApplication.translate("Window", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.LoginLabel.setText(QtGui.QApplication.translate("Window", "Login:", None, QtGui.QApplication.UnicodeUTF8))
        self.PasswordLabel.setText(QtGui.QApplication.translate("Window", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Window", "Войти", None, QtGui.QApplication.UnicodeUTF8))

class Ui_buttons(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(478, 289)
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 481, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ShowClient = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.ShowClient.setFont(font)
        self.ShowClient.setObjectName("ShowClient")
        self.verticalLayout.addWidget(self.ShowClient)
        self.DeleteClient = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.DeleteClient.setFont(font)
        self.DeleteClient.setObjectName("DeleteClient")
        self.verticalLayout.addWidget(self.DeleteClient)
        self.ReNameClient = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.ReNameClient.setFont(font)
        self.ReNameClient.setObjectName("ReNameClient")
        self.verticalLayout.addWidget(self.ReNameClient)
        self.AddClient = QtGui.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.AddClient.setFont(font)
        self.AddClient.setObjectName("AddClient")
        self.verticalLayout.addWidget(self.AddClient)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.ShowClient.setText(
                QtGui.QApplication.translate("Form", "Показать клиентов", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteClient.setText(
                QtGui.QApplication.translate("Form", "Удалить Клиента", None, QtGui.QApplication.UnicodeUTF8))
        self.ReNameClient.setText(
                QtGui.QApplication.translate("Form", "Изменить Клиента", None, QtGui.QApplication.UnicodeUTF8))
        self.AddClient.setText(
                QtGui.QApplication.translate("Form", "Добавить клента", None, QtGui.QApplication.UnicodeUTF8))

class Ui_Data(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(852, 295)
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 851, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lbl.setFont(font)
        self.lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl.setObjectName("lbl")
        self.verticalLayout.addWidget(self.lbl)
        self.gridLayoutWidget = QtGui.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, 59, 851, 92))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateTimeEdit.setFrame(False)
        self.dateTimeEdit.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.dateTimeEdit.setKeyboardTracking(False)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.dateTimeEdit_2.setFont(font)
        self.dateTimeEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateTimeEdit_2.setFrame(False)
        self.dateTimeEdit_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_2.setKeyboardTracking(False)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout.addWidget(self.dateTimeEdit_2, 1, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl.setText(QtGui.QApplication.translate("Form", "Клиенты на сегодня", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Клиент", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Парикхмахер", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Время начала", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Время окончания", None, QtGui.QApplication.UnicodeUTF8))